name: Linux CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  DESTDIR: ${{github.workspace}}/barcelona-trees-v0.0.6-x86_64.AppDir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.*'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: 'qtlocation qtpositioning'

    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -yq libarchive-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: |
        mkdir -p ${{env.DESTDIR}}
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Compress AppDir
      run: tar -cvzf -C ${{github.workspace}} barcelona-trees-v0.0.6-x86_64.AppDir.tar.gz barcelona-trees-v0.0.6-x86_64.AppDir

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        path: barcelona-trees-v0.0.6-x86_64.AppDir.tar.gz
        archive: false
        retention-days: 90
        overwrite: true
