name: Linux CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟥', arch: "x86_64",  os: "ubuntu-22.04", host: "linux" }
          - { icon: '🟩', arch: "aarch64", os: "ubuntu-24.04-arm", host: "linux_arm64" }
    runs-on: ${{ matrix.os }}
    name: 🚧${{ matrix.icon }} ${{ matrix.arch }}

    steps:
    - name: '${{ matrix.icon }} Checkout recursive'
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: '${{ matrix.icon }} Install Dependencies'
      run: sudo apt-get update && sudo apt-get install -yq libarchive-dev libgl-dev libvulkan-dev

    - name: '${{ matrix.icon }} Install Qt'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.1'
        host: ${{ matrix.host }}
        target: 'desktop'
        modules: 'qtlocation qtpositioning qttasktree'

    - name: '${{ matrix.icon }} Configure CMake'
      id: configuration
      run: cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_INSTALL_LIBDIR=lib
        -DCMAKE_INSTALL_RPATH="\$ORIGIN/../lib"

    - name: '${{ matrix.icon }} Build'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Install'
      env:
        DESTDIR: ${{github.workspace}}/build/barcelona-trees-v${{steps.configuration.outputs.config_version}}-${{ matrix.arch }}.AppDir
      run: |
        mkdir -p ${{env.DESTDIR}}
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Compress AppDir'
      run: |
        cd ${{github.workspace}}/build
        tar cvzf barcelona-trees-v${{steps.configuration.outputs.config_version}}-${{ matrix.arch }}.AppDir.tar.gz barcelona-trees-v${{steps.configuration.outputs.config_version}}-${{ matrix.arch }}.AppDir

    - name: '${{ matrix.icon }} Upload Artifact'
      uses: actions/upload-artifact@v7
      with:
        path: ${{github.workspace}}/build/barcelona-trees-v${{steps.configuration.outputs.config_version}}-${{ matrix.arch }}.AppDir.tar.gz
        archive: false
        retention-days: 90
        overwrite: true

    - name: '${{ matrix.icon }} Upload AppImage'
      uses: actions/upload-artifact@v7
      with:
        path: ${{github.workspace}}/build/barcelona-trees-v${{steps.configuration.outputs.config_version}}-${{ matrix.arch }}.AppImage
        archive: false
        retention-days: 90
        overwrite: true
