name: Linux CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.*'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: 'qtlocation qtpositioning'

    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -yq libarchive-dev

    - name: Configure CMake
      id: configuration
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      env:
        DESTDIR: ${{github.workspace}}/barcelona-trees-v${{steps.configuration.outputs.config_version}}-x86_64.AppDir
      run: |
        mkdir -p ${{env.DESTDIR}}
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Compress AppDir
      run: |
        cd ${{github.workspace}}
        tar -cvzf barcelona-trees-v${{steps.configuration.outputs.config_version}}-x86_64.AppDir.tar.gz barcelona-trees-v${{steps.configuration.outputs.config_version}}-x86_64.AppDir

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        path: barcelona-trees-v${{steps.configuration.outputs.config_version}}-x86_64.AppDir.tar.gz
        archive: false
        retention-days: 90
        overwrite: true
